camel:
  springboot:
    main-run-controller: true
spring:
  application:
    name: Integration-Brunel-CEVA_SAP-WHSCON_SHPCON

ftp:
  ceva:
    server: ukftp-auto.oup.com
    pickuplocation: 
      plant1: to_OUP/IN-SON-01/RECADV
      plant2: to_OUP/IN-CHE-01/RECADV
    port: 22
    username: brunel_test_OUP
    password: RAW(!D9ElUcMktDLIqd&J^6Ye)
    fileFilter: cevaextract_*.xml
    ftpOptions: username=${ftp.ceva.username}&password=${ftp.ceva.password}&antInclude=${ftp.ceva.fileFilter}&useUserKnownHostsFile=false&delete=true&sortBy=file:modified
    sftpPathPlant1: file:plant_7410
    sftpPathPlant2: file:plant_7430

sap:
  connection:
    gwhost: 10.45.6.7
    gwserv: sapgw00
    progid: IND_BRUNEL_INBOUND
    client: 174
    user: BRUNEL
    passwd: Welcome@1
    lang: EN
    group: 
    mshost: 10.45.6.7
    msserv: 3600
    r3name: IND
    connectionCount: 2
    recipientPort: SAPIND
    recipientPartnerNumber: CEVA_INDEL
    senderPort: BRUNEL_INBOUND
    senderPartnerNumber: CEVAWH
    idocType: DELVRY03
    messageType: WHSCON
    endpoint: sap-idoc-destination:sapInbound:DELVRY03

file:
  location: backup
  XML: 
    name: RECADV-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/01-FromCEVA/$simple{date:now:yyyy/MM/dd}
  IDOC: 
    name: $simple{header.messageType}-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/02-ToSAP/$simple{date:now:yyyy/MM/dd}

---

spring:
  profiles: dev

ftp:
  ceva:
    server: ukftp-auto.oup.com
    pickuplocation: 
      plant1: to_OUP/IN-SON-01/RECADV
      plant2: to_OUP/IN-CHE-01/RECADV
    port: 22
    username: brunel_test_OUP
    password: RAW(!D9ElUcMktDLIqd&J^6Ye)
    fileFilter: cevaextract_*.xml
    ftpOptions: username=${ftp.ceva.username}&password=${ftp.ceva.password}&useUserKnownHostsFile=false&delete=true&sortBy=file:modified
    sftpPathPlant1: sftp:{{ftp.ceva.server}}/{{ftp.ceva.pickuplocation.plant1}}?{{ftp.ceva.ftpOptions}}
    sftpPathPlant2: sftp:{{ftp.ceva.server}}/{{ftp.ceva.pickuplocation.plant2}}?{{ftp.ceva.ftpOptions}}

sap:
  connection:
    gwhost: 10.45.6.7
    gwserv: sapgw00
    progid: IND_BRUNEL_INBOUND
    client: 174
    user: BRUNEL
    passwd: Welcome@1
    lang: EN
    group: 
    mshost: 10.45.6.7
    msserv: 3600
    r3name: IND
    connectionCount: 2
    recipientPort: SAPIND
    recipientPartnerNumber: CEVA_INDEL
    senderPort: BRUNEL_INBOUND
    senderPartnerNumber: CEVAWH
    idocType: DELVRY03
    messageType: WHSCON
    endpoint: sap-idoc-destination:sapInbound:DELVRY03

file:
  location: /OUT/${spring.application.name}/dev
  XML: 
    name: RECADV-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/01-FromCEVA/$simple{date:now:yyyy/MM/dd}
  IDOC: 
    name: WHSCON-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/02-ToSAP/$simple{date:now:yyyy/MM/dd}

---

spring:
  profiles: uat

ftp:
  ceva:
    server: ukftp-auto.oup.com
    pickuplocation: 
      plant1: to_OUP/IN-SON-01/RECADV
      plant2: to_OUP/IN-CHE-01/RECADV
    port: 22
    username: brunel_test_OUP
    password: RAW(!D9ElUcMktDLIqd&J^6Ye)
    fileFilter: .*.xml
    ftpOptions: username=${ftp.ceva.username}&password=${ftp.ceva.password}&useUserKnownHostsFile=false&delete=true&sortBy=file:modified
    sftpPathPlant1: sftp:{{ftp.ceva.server}}/{{ftp.ceva.pickuplocation.plant1}}?{{ftp.ceva.ftpOptions}}
    sftpPathPlant2: sftp:{{ftp.ceva.server}}/{{ftp.ceva.pickuplocation.plant2}}?{{ftp.ceva.ftpOptions}}

sap:
  connection:
    gwhost: 10.45.6.58
    gwserv: sapgw00
    progid: INQ_BRUNEL_INBOUND
    client: 74
    user: TEST_BRUNEL
    passwd: Welcome@1
    lang: EN
    group: 
    mshost: 10.45.6.58
    msserv: 3601
    r3name: INQ
    connectionCount: 2
    recipientPort: SAPINQ
    recipientPartnerNumber: CEVA_INDEL
    senderPort: BRUNEL_INBOUND
    senderPartnerNumber: CEVAWH
    idocType: DELVRY03
    messageType: WHSCON
    endpoint: sap-idoc-destination:sapInbound:DELVRY03

file:
  location: /OUT/${spring.application.name}/uat
  XML: 
    name: RECADV-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/01-FromCEVA/$simple{date:now:yyyy/MM/dd}
  IDOC: 
    name: WHSCON-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/02-ToSAP/$simple{date:now:yyyy/MM/dd}
